spring:
  profiles:
    active: window-dev
---
server:
  port: 0

logging:
  level:
    yongs:
      temp: DEBUG
    com:
      netflix:
        eureka: OFF
        discovery: OFF  
      
spring:
  profiles: window-dev
  application:
    name: yongs-stock  
  sleuth:
    sampler:
      probability: 1
  zipkin:
    baseUrl: http://localhost:9411/
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27027/order
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: stock
      enable-auto-commit: false
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual-immediate
                      
eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
    instanceId: ${spring.application.name}:${random.value}
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

---
server:
  port: 8080

logging:
  level:
    yongs:
      temp: INFO
    com:
      netflix:
        eureka: OFF
        discovery: OFF  
      
spring:
  profiles: container
  application:
    name: yongs-stock  
  sleuth:
    sampler:
      probability: 1
  zipkin:
    baseUrl: http://zipkin:9411/
  data:
    mongodb:
      uri: mongodb://order-mongo:27027/order
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: stock
      enable-auto-commit: false
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual-immediate
                      
eureka:
  instance:
    preferIpAddress: true
    hostname: eureka
    instanceId: ${spring.application.name}:${random.value}
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      